/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class TelaAlterarConta extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlterarConta
     */
    public TelaAlterarConta() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        StxtSenha.setVisible(false);
        FtxtTelefone.setVisible(false);
    }

    private void EnderecoEscolhido(){
        TxtAlteracao.setVisible(true);
        StxtSenha.setVisible(false);
        FtxtTelefone.setVisible(false);
    }
    
    private void TelefoneEscolhido(){
        TxtAlteracao.setVisible(false);
        StxtSenha.setVisible(false);
        FtxtTelefone.setVisible(true);
    }
    
    private void EmailEscolhido(){
        TxtAlteracao.setVisible(true);
        StxtSenha.setVisible(false);
        FtxtTelefone.setVisible(false);
    }
    
    private void SenhaEscolhido(){
        TxtAlteracao.setVisible(false);
        StxtSenha.setVisible(true);
        FtxtTelefone.setVisible(false);
    }
    
    private String Escolher(){
        String escolhido = (String) CboxAlternar.getSelectedItem();
        switch(escolhido){
            case "Endereco" -> EnderecoEscolhido();
            case "Telefone" -> TelefoneEscolhido();
            case "Email" -> EmailEscolhido();
            case "Senha" -> SenhaEscolhido();
            default -> JOptionPane.showMessageDialog(this, "Invalid action! Please try again.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
        return escolhido;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CboxAlternar = new javax.swing.JComboBox<>();
        RotAlterar = new javax.swing.JLabel();
        BtVoltar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        RotAlteracao = new javax.swing.JLabel();
        TxtAlteracao = new javax.swing.JTextField();
        FtxtTelefone = new javax.swing.JFormattedTextField();
        StxtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CboxAlternar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Endereco", "Telefone", "Email", "Senha" }));
        CboxAlternar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxAlternarActionPerformed(evt);
            }
        });
        getContentPane().add(CboxAlternar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 232, -1));

        RotAlterar.setText("O que deseja alterar:");
        getContentPane().add(RotAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 110, -1, -1));

        BtVoltar.setText("Voltar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 285, -1, -1));

        BtAlterar.setText("Alterar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(BtAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 285, -1, -1));

        RotAlteracao.setText("Alteração:");
        getContentPane().add(RotAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 172, -1, -1));

        TxtAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAlteracaoActionPerformed(evt);
            }
        });
        getContentPane().add(TxtAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 169, 286, -1));

        try {
            FtxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(FtxtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 110, -1));

        StxtSenha.setToolTipText("");
        getContentPane().add(StxtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaConta tc = new TelaConta();
    }//GEN-LAST:event_BtVoltarActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        // TODO add your handling code here:
        //TelaVerificacao tv = new TelaVerificacao();
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void CboxAlternarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxAlternarActionPerformed
        // TODO add your handling code here:
        Escolher();
    }//GEN-LAST:event_CboxAlternarActionPerformed

    private void TxtAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAlteracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAlteracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JComboBox<String> CboxAlternar;
    private javax.swing.JFormattedTextField FtxtTelefone;
    private javax.swing.JLabel RotAlteracao;
    private javax.swing.JLabel RotAlterar;
    private javax.swing.JPasswordField StxtSenha;
    private javax.swing.JTextField TxtAlteracao;
    // End of variables declaration//GEN-END:variables
}
