/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Cliente;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author pedro
 */
public class TelaConta extends javax.swing.JFrame {
    private Cliente cliente;

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    /**
     * Creates new form TelaConta
     */
    public TelaConta() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public TelaConta(Cliente c) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setCliente(c);
        MostrarConta();
    }
    
    private void MostrarConta(){
        ValorNome.setText(cliente.getNome());
        ValorCpf.setText(cliente.getCpf());
        ValorData.setText(cliente.getDataNascimento());
        ValorEmail.setText(cliente.getEmail());
        ValorGenero.setText(cliente.getGenero());
        ValorTelefone.setText(cliente.getTelefone());
        ValorEndereco.setText(cliente.getEndereco());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RotInformacao = new javax.swing.JLabel();
        BtVoltar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtRemover = new javax.swing.JButton();
        RotNome = new javax.swing.JLabel();
        RotData = new javax.swing.JLabel();
        RotCpf = new javax.swing.JLabel();
        RotGenero = new javax.swing.JLabel();
        RotTelefone = new javax.swing.JLabel();
        RotEndereco = new javax.swing.JLabel();
        RotEmail = new javax.swing.JLabel();
        ValorNome = new javax.swing.JLabel();
        ValorData = new javax.swing.JLabel();
        ValorCpf = new javax.swing.JLabel();
        ValorGenero = new javax.swing.JLabel();
        ValorTelefone = new javax.swing.JLabel();
        ValorEmail = new javax.swing.JLabel();
        ValorEndereco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RotInformacao.setText("Dados da conta:");

        BtVoltar.setText("Voltar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        BtAlterar.setText("Alterar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtRemover.setText("Remover");
        BtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverActionPerformed(evt);
            }
        });

        RotNome.setText("Nome:");

        RotData.setText("Data de Nascimento:");

        RotCpf.setText("CPF:");

        RotGenero.setText("Gênero:");

        RotTelefone.setText("Telefone:");

        RotEndereco.setText("Endereço:");

        RotEmail.setText("Email:");

        ValorNome.setText("NOME USUÁRIO");

        ValorData.setText("17/05/2002");

        ValorCpf.setText("748.849.920-34");

        ValorGenero.setText("MASCULINO");

        ValorTelefone.setText("(11) 96273-9392");

        ValorEmail.setText("USUÁRIO@GMAIL");

        ValorEndereco.setText("Rua Alguma coisa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(BtAlterar)
                        .addGap(128, 128, 128)
                        .addComponent(BtRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(BtVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RotNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RotGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorGenero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RotEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RotEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RotTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorTelefone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RotCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorCpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RotData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorData))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(RotInformacao)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(RotInformacao)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotNome)
                    .addComponent(ValorNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotData)
                    .addComponent(ValorData))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotCpf)
                    .addComponent(ValorCpf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotGenero)
                    .addComponent(ValorGenero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotTelefone)
                    .addComponent(ValorTelefone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotEndereco)
                    .addComponent(ValorEndereco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotEmail)
                    .addComponent(ValorEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAlterar)
                    .addComponent(BtRemover))
                .addGap(18, 18, 18)
                .addComponent(BtVoltar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaPrincipal tp = new TelaPrincipal();
    }//GEN-LAST:event_BtVoltarActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaAlterarConta tac = new TelaAlterarConta();
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverActionPerformed
        // TODO add your handling code here:
        TelaVerificacao tv = new TelaVerificacao();
    }//GEN-LAST:event_BtRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtRemover;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JLabel RotCpf;
    private javax.swing.JLabel RotData;
    private javax.swing.JLabel RotEmail;
    private javax.swing.JLabel RotEndereco;
    private javax.swing.JLabel RotGenero;
    private javax.swing.JLabel RotInformacao;
    private javax.swing.JLabel RotNome;
    private javax.swing.JLabel RotTelefone;
    private javax.swing.JLabel ValorCpf;
    private javax.swing.JLabel ValorData;
    private javax.swing.JLabel ValorEmail;
    private javax.swing.JLabel ValorEndereco;
    private javax.swing.JLabel ValorGenero;
    private javax.swing.JLabel ValorNome;
    private javax.swing.JLabel ValorTelefone;
    // End of variables declaration//GEN-END:variables
}
