/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class TelaDeposito extends javax.swing.JFrame {

    /**
     * Creates new form TelaDepósito
     */
    public TelaDeposito() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        //já atualizar automaticamento o saldo da pessoa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RotSaldo = new javax.swing.JLabel();
        RotReais = new javax.swing.JLabel();
        RotDinheiro = new javax.swing.JLabel();
        RotValor = new javax.swing.JLabel();
        BtDepositar = new javax.swing.JButton();
        BtVoltar = new javax.swing.JButton();
        TxtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RotSaldo.setText("Saldo em conta:");

        RotReais.setText("R$");

        RotDinheiro.setText("00.00");

        RotValor.setText("Valor:");

        BtDepositar.setText("Depositar");
        BtDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDepositarActionPerformed(evt);
            }
        });

        BtVoltar.setText("Voltar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RotSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RotReais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RotDinheiro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RotValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtDepositar)
                            .addComponent(TxtValor))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotSaldo)
                    .addComponent(RotReais)
                    .addComponent(RotDinheiro))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotValor)
                    .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(BtDepositar)
                .addGap(27, 27, 27)
                .addComponent(BtVoltar)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDepositarActionPerformed
        // TODO add your handling code here:
        //TelaVerificacao tv = new TelaVerificacao();
        String stringValor = (String) TxtValor.getText();
        String stringRotulo = RotDinheiro.getText();
        System.out.println(stringValor);
        try{
            float quantidade = (Float.valueOf(stringValor)).floatValue();
            System.out.println(quantidade);
            float valor = (Float.valueOf(stringRotulo)).floatValue();
            valor = valor + quantidade;
            DecimalFormat df = new DecimalFormat("#.##");
            String valorDecimal = df.format(valor);
            RotDinheiro.setText(Float.toString(valor));
        }
        catch(NumberFormatException e){
            System.out.println("Erro: "+e);
            JOptionPane.showMessageDialog(this, "Número invpalido",
                        "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
      
        //RotDinheiro.setText(s);
        //DAO
    }//GEN-LAST:event_BtDepositarActionPerformed

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaPrincipal tp = new TelaPrincipal();
    }//GEN-LAST:event_BtVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtDepositar;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JLabel RotDinheiro;
    private javax.swing.JLabel RotReais;
    private javax.swing.JLabel RotSaldo;
    private javax.swing.JLabel RotValor;
    private javax.swing.JTextField TxtValor;
    // End of variables declaration//GEN-END:variables
}
